/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        heading: ['Barlow', 'sans-serif'],
        body: ['Open Sans', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: '#2e1a99',
          50: '#eeebfb',
          100: '#d5cdf3',
          200: '#ab9be7',
          300: '#8069db',
          400: '#5637cf',
          500: '#2e1a99',
          600: '#25157b',
          700: '#1c105c',
          800: '#130a3e',
          900: '#09051f',
        },
        secondary: {
          DEFAULT: '#5637cf',
          50: '#f0edfb',
          100: '#dad0f5',
          200: '#b5a1eb',
          300: '#8f72e1',
          400: '#6a43d7',
          500: '#5637cf',
          600: '#442ca6',
          700: '#33207c',
          800: '#221553',
          900: '#110a29',
        },
        accent: {
          DEFAULT: '#4ade80',
          50: '#eefdf3',
          100: '#d5fae1',
          200: '#abf5c3',
          300: '#81f0a5',
          400: '#5ce88a',
          500: '#4ade80',
          600: '#2fb35d',
          700: '#248646',
          800: '#185a2f',
          900: '#0c2d17',
        },
        success: '#28a745',
        warning: '#ffc107',
        error: '#dc3545',
        brand: {
          red: '#a44b4b',
          gold: '#bba46a',
          seabukhthon: '#f5a23f',
          polmazox: '#4757a6',
          darkgold: '#f07e02',
          bonefrax: '#f6843b',
          lomocal: '#faba7a',
          palmimax: '#e86f40',
        },
      },
      keyframes: {
        'slide-left': {
          '0%': { transform: 'translateX(0)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        'fade-up': {
          '0%': { opacity: '0', transform: 'translateY(30px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'slide-in-right': {
          '0%': { opacity: '0', transform: 'translateX(60px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'slide-in-left': {
          '0%': { opacity: '0', transform: 'translateX(-60px)' },
          '100%': { opacity: '1', transform: 'translateX(0)' },
        },
        'scale-in': {
          '0%': { opacity: '0', transform: 'scale(0.9)' },
          '100%': { opacity: '1', transform: 'scale(1)' },
        },
        'bounce-slow': {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'spin-slow': {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        'pulse-ring': {
          '0%': { transform: 'scale(0.8)', opacity: '0.8' },
          '100%': { transform: 'scale(2)', opacity: '0' },
        },
      },
      animation: {
        'slide-left': 'slide-left 30s linear infinite',
        'fade-up': 'fade-up 0.8s ease-out forwards',
        'fade-in': 'fade-in 0.6s ease-out forwards',
        'slide-in-right': 'slide-in-right 0.8s ease-out forwards',
        'slide-in-left': 'slide-in-left 0.8s ease-out forwards',
        'scale-in': 'scale-in 0.6s ease-out forwards',
        'bounce-slow': 'bounce-slow 3s ease-in-out infinite',
        'spin-slow': 'spin-slow 20s linear infinite',
        'pulse-ring': 'pulse-ring 2s ease-out infinite',
      },
    },
  },
  plugins: [],
};
